vim.cmd.packadd("gitsigns.nvim")
require("gitsigns").setup()

vim.keymap.set("n", "]h", function()
    require("gitsigns").next_hunk()
end, { desc = "Next Hunk" })

local keyset = vim.keymap.set

keyset("n", "]h", function()
    require("gitsigns").next_hunk()
end, { desc = "Next git hunk" })
keyset("n", "[h", function()
    require("gitsigns").prev_hunk()
end, { desc = "Previous git hunk" })
keyset("n", "<leader>hs", function()
    require("gitsigns").stage_hunk()
end, { desc = "Stage hunk" })
keyset("n", "<leader>hr", function()
    require("gitsigns").reset_hunk()
end, { desc = "Reset hunk" })
keyset("n", "<leader>hp", function()
    require("gitsigns").preview_hunk()
end, { desc = "Preview hunk" })
keyset("n", "<leader>hb", function()
    require("gitsigns").blame_line({ full = true })
end, { desc = "Blame line" })
keyset("n", "<leader>hB", function()
    require("gitsigns").toggle_current_line_blame()
end, { desc = "Toggle inline blame" })
keyset("n", "<leader>hd", function()
    require("gitsigns").diffthis()
end, { desc = "Diff this" })
